name: Daily ZUT Practice Checker

on:
  schedule:
    - cron: '0 7 * * *'  # Every day at 07:00 UTC (09:00 PL)
  workflow_dispatch:

jobs:
  check-practice:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitor script
        run: python monitor.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Commit hash files to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add last_hash.txt || echo "last_hash.txt not found"
          git add prev_hash.txt || echo "prev_hash.txt not found"
          git commit -m "Update hash files [bot]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
