name: Daily ZUT Practice Checker

on:
  schedule:
    - cron: '0 7 * * *'  # Daily at 7:00 UTC
  workflow_dispatch:

jobs:
  check-practice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - run: python monitor.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Upload hash files
        uses: actions/upload-artifact@v4
        with:
          name: hash-files
          path: |
            last_hash.txt
            prev_hash.txt

